import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";
import { Header } from "@/components/shared/AppNavbar";
import { endpoints } from "@/api/endpoints";
import { fetcher } from "@/api/fetcher";

export type TCategory = {
  id: number;
  name: string;
  slug: string;
  description: string;
  image: string;
};
interface ICategoriesResponse {
  success: boolean;
  data: {
    categories: TCategory[];
    total: number;
  };
}

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const res = await fetcher<ICategoriesResponse>(endpoints.categories());
  console.log(res, "check res");
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased max-w-330 mx-auto`}
      >
        <Header categories={res.data.categories} />
        <main>{children}</main>
      </body>
    </html>
  );
}
